import Login from 'components/Authentication/login.component';
import Profile from 'components/Authentication/profile.component';
import Register from 'components/Authentication/register.component';
import About from 'pages/About';
import ApplicationForm from 'pages/ApplicationForm/ApplicationForm';
import ApplicationFormSuccess from 'pages/ApplicationFormSuccess/ApplicationFormSuccess';
import BlogList from 'pages/Blogs/BlogListPage';
import Blogpost from 'pages/Blogs/Blogpost';
import BlogType from 'pages/Blogs/BlogType';
import EditBlog from 'pages/Blogs/EditBlog';
import Home from 'pages/Home/Home';
import Leadership from 'pages/Leadership';
import Privacy from 'pages/Legal/Privacy';
import Terms from 'pages/Legal/Terms';
import Mentors from 'pages/Mentors';
import Program from 'pages/Program';
import Stories from 'pages/Stories/Stories';

export const HOME = Home;
export const EDIT_BLOG = EditBlog;
export const BLOG_TYPE = BlogType;
export const BLOG_LIST = BlogList;
export const APPLICATION_FORM = ApplicationForm;
export const MENTORS = Mentors;
export const PROGRAM = Program;
export const ABOUT = About;
export const STORIES = Stories;
export const APPLICATION_FORM_SUCCESS = ApplicationFormSuccess;
export const EDITBLOG = EditBlog;
export const BLOGTYPE = BlogType;
export const APPLICATIONFORM = ApplicationForm;
export const BLOGPOST = Blogpost;
export const PRIVACY = Privacy;
export const TERMS = Terms;
export const LEADERSHIP = Leadership;
export const LOGIN = Login;
export const REGISTER = Register;
export const PROFILE = Profile;
