FROM node:14.4.0-alpine3.12 as builder

WORKDIR /app/frontend

# Install dependencies
COPY package.json /app/frontend
COPY yarn.lock /app/frontend
RUN yarn install

# Copy Code
COPY . /app/frontend

RUN yarn build

FROM nginx:1.19-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/frontend/build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
