version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ismp_development
      POSTGRES_USER: ismp
      POSTGRES_PASSWORD: "password"

  # Create separate DB for running backend tests
  test_postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ismp_test
      POSTGRES_USER: ismp
      POSTGRES_PASSWORD: "test"

  load_balancer:
    image: nginx:1.19-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    image: "localhost/ismp/backend:snapshot"
    volumes:
      - ./backend:/app/api
    environment: &BACKEND_ENV
      USE_S3: "FALSE"
      AWS_ACCESS_KEY_ID: "foobar_key"
      AWS_SECRET_ACCESS_KEY: "foobar_secret"
      AWS_STORAGE_BUCKET_NAME: "fake_bucket_lalala"
      USE_MAILCHIMP: 'FALSE'
      MAILCHIMP_USERNAME: 'foobar'
      MAILCHIMP_API_KEY: 'foobar_api_key'
      MAILCHIMP_LIST_ID: 'foobar_list_id'
      ALLOWED_HOST: 'backend'
      DB_DATABASE: ismp_development
      DB_HOST: postgres
      DB_PASSWORD: "password"
      DB_PORT: 5432
      DB_USER: ismp
      DEBUG: 'TRUE'
      LOGGING_LEVEL: 'ERROR'
      # this is not the key that will be used in production. Also please note
      # that in environment variables in docker-compose.yml, you have to
      # escape the $ character with another $ ($$).
      DJANGO_SECRET_KEY: "this_is_not_a_real_secret_key"
    depends_on:
      - postgres

  backend_db_migrations:
    image: "localhost/ismp/backend:snapshot"
    volumes:
      - ./backend:/app/api
    environment:
      <<: *BACKEND_ENV
    command: /app/api/run_migrations.sh
    depends_on:
      - postgres
      # `backend_db_migrations` depends on the image built by `backend`
      - backend

  frontend:
    image: "localhost/ismp/frontend_dev:snapshot"
    build: ./frontend
    environment:
      REACT_APP_AWS_STORAGE_BUCKET_NAME:
      # TODO: Remove CI=true after https://github.com/facebook/create-react-app/pull/8845
      CI: "true"
    volumes:
      # Overwrite docker image's src directories with locally modified code
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
