# Generated by Django 3.0.7 on 2020-06-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_content', '0007_auto_20200602_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcontent',
            name='author_display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blogpostcontent',
            name='preview_text',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
