# Generated by Django 3.0.7 on 2020-06-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_auto_20200610_2115'),
        ('blogpost', '0011_blogpost_thumbnail_url'),
    ]

    operations = [
    ]
