# Generated by Django 3.0.7 on 2020-06-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0013_merge_20200612_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='display_text',
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='nihao', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
