# Generated by Django 3.0.7 on 2020-06-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0008_auto_20200608_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttopic',
            name='ApplicationForm',
        ),
        migrations.AddField(
            model_name='interesttopic',
            name='application_form',
            field=models.ManyToManyField(related_name='interest_topics', to='application_form.ApplicationForm'),
        ),
    ]
