# Generated by Django 3.0.7 on 2020-06-13 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0009_auto_20200612_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
