# Generated by Django 3.0.7 on 2020-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0012_remove_applicationform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='additional_input',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='school_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='school_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
